In [1]:
import tensorflow as tf
import numpy as np

In [13]:
x = np.zeros((1, 256, 78))
conv1 = tf.keras.layers.Conv1D(1, 11, padding="valid", activation="relu")
conv1(x)

<tf.Tensor: shape=(1, 246, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [

In [6]:

conv2 = tf.keras.layers.Conv1D(256, 11, padding="same", activation="relu")
conv3 = tf.keras.layers.Conv1D(256, 11, padding="same", activation="relu")

In [8]:
x = conv1(x)

In [9]:
conv2(x)

<tf.Tensor: shape=(1, 256, 256), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>

In [14]:
def positional_encoding(length, depth):
    depth = depth/2

    positions = np.arange(length)[:, np.newaxis]     # (seq, 1)
    depths = np.arange(depth)[np.newaxis, :]/depth   # (1, depth)
    
    angle_rates = 1 / (10000**depths)         # (1, depth)
    angle_rads = positions * angle_rates      # (pos, depth)

    pos_encoding = np.concatenate(
        [np.sin(angle_rads), np.cos(angle_rads)],
        axis=-1) 

    return tf.cast(pos_encoding, dtype=tf.float32)

In [15]:
positional_encoding(10, 2)

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[ 0.        ,  1.        ],
       [ 0.84147096,  0.5403023 ],
       [ 0.9092974 , -0.41614684],
       [ 0.14112   , -0.9899925 ],
       [-0.7568025 , -0.6536436 ],
       [-0.9589243 ,  0.2836622 ],
       [-0.2794155 ,  0.96017027],
       [ 0.6569866 ,  0.75390226],
       [ 0.98935825, -0.14550003],
       [ 0.4121185 , -0.91113025]], dtype=float32)>